version: '3.8'

x-db-varibles: &db-varibles
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: luxonis

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      <<: *db-varibles
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5

  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "8080:8080"
      - "3000:3000"

  api:
    build:
      dockerfile: Dockerfile
      context: "./server"
    depends_on:
      - db
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      <<: *db-varibles
    links:
      - db

  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app

  scraper:
    build:
      dockerfile: Dockerfile
      context: ./scraper
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./scraper:/app
    command: python3 ./main.py
    links:
      - db

  adminer:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8000:8080
    environment:
      - ADMINER_DEFAULT_SERVER=db